/// Generate a TOML config template for the given parameters.
pub fn config_toml(
    name: &str,
    source_type: &str,
    query_type: &str,
    output_formats: &[String],
) -> String {
    let formats_str = output_formats
        .iter()
        .map(|f| format!("\"{}\"", f))
        .collect::<Vec<_>>()
        .join(", ");

    let query_section = match query_type {
        "file" => format!(
            r#"[query]
file = "./queries/{name}.sparql"    # Path to SPARQL query file
base_iri = "http://example.org/""#
        ),
        _ => r#"[query]
# Inline SPARQL query
query = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?subject ?predicate ?object
WHERE {
    ?subject ?predicate ?object .
}
LIMIT 100
"""
base_iri = "http://example.org/""#
            .to_string(),
    };

    let source_section = match source_type {
        "s3" => r#"# S3 source configuration
# Authentication: set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables
[[sources]]
type = "s3"
bucket = "my-bucket"                      # S3 bucket name
prefix = "data/"                          # Prefix (folder) within the bucket
region = "eu-west-1"                      # AWS region
# endpoint = "http://localhost:9000"      # Uncomment for S3-compatible services (MinIO, etc.)
patterns = ["*.xml", "*.rdf"]"#
            .to_string(),
        "azure" => r#"# Azure Blob Storage source configuration
# Authentication: set AZURE_STORAGE_ACCOUNT_KEY environment variable
[[sources]]
type = "azure"
account = "mystorageaccount"              # Storage account name
container = "mycontainer"                 # Container name
prefix = "data/"                          # Prefix (folder) within the container
# endpoint = "http://127.0.0.1:10000"    # Uncomment for Azurite emulator
patterns = ["*.xml", "*.rdf"]"#
            .to_string(),
        "gcs" => r#"# Google Cloud Storage source configuration
# Authentication: set GOOGLE_APPLICATION_CREDENTIALS environment variable
[[sources]]
type = "gcs"
bucket = "my-bucket"                      # GCS bucket name
prefix = "data/"                          # Prefix (folder) within the bucket
# endpoint = "http://localhost:4443"      # Uncomment for fake-gcs-server emulator
patterns = ["*.xml", "*.rdf"]"#
            .to_string(),
        _ => r#"# Local filesystem source
[[sources]]
type = "local"
path = "./data"                           # Path to directory containing RDF files
patterns = ["*.xml", "*.rdf", "*.zip", "*.gz"]
recursive = true"#
            .to_string(),
    };

    format!(
        r#"# Cimishi Pipeline Configuration — {name}
# Generated by `cimishi init`

[pipeline]
name = "{name}"
parallel = true
max_concurrent = 10

# =============================================================================
# SOURCES
# =============================================================================

{source_section}

# =============================================================================
# PROCESSORS — uncomment to enable
# =============================================================================

# Uncomment to enable ZIP/GZIP decompression:
# [[processors]]
# type = "unzip"
# archive_patterns = ["*.zip"]
# gzip_patterns = ["*.gz", "*.gzip"]
# patterns = ["*.xml", "*.rdf"]

# Uncomment to filter files:
# [[processors]]
# type = "filter"
# include = ["*_EQ_*.xml", "*_TP_*.xml"]
# exclude = ["*_BD_*.xml"]

# =============================================================================
# QUERY
# =============================================================================

{query_section}

# =============================================================================
# OUTPUT
# =============================================================================

[output]
dir = "./output"
formats = [{formats_str}]
metadata = true
prefix = "results"
"#
    )
}

/// Generate a default SPARQL query file.
pub fn sparql_query() -> &'static str {
    r#"# Default SPARQL query — edit to match your RDF schema
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX cim: <http://iec.ch/TC57/CIM100#>
PREFIX md: <http://iec.ch/TC57/61970-552/ModelDescription/1#>

SELECT ?subject ?predicate ?object
WHERE {
    ?subject ?predicate ?object .
}
LIMIT 100
"#
}
